st=str(input('Enter a string : '))
st1=input('enter the spacing : ')
print('The string entered is a word : ',st.isalpha())
print('The string entered in lower case : ',st.lower())
print('The string entered is in lower case : ',st.islower())
print('The string entered in upper case : ',st.upper())
print('The string entered is in upper case : ',st.isupper())
print('The string entered after removing the spaces from left side',st.lstrip())
print('The string entered after removing the spaces from right side',st.rstrip())
print('The string entered contains white space : ',st.isspace())
print('The string entered is titlecased : ',st.istitle())
print('The string entered after joining with ',st1,' : ',st1.join(st))
print('The string entered after swaping case : ',st.swapcase())
